### ISSUE TITLE
回覧板モジュール未インストールで移行エラー

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#1027]
2.4.0.0から2.4.2.1にバージョンアップしてから移行しました。
回覧板(2.4.1.0)は左のバージョンで入ってきたので、未インストールでした。
報告まで。

### エラーログ

```
2017-09-15 02:28:53 Debug: CircularNotice Migration start. : Nc2ToNc3CircularNotice on line 54
Error: Table netcommons2_circular_block for model Nc2CircularBlock was not found in datasource nc2.
#0 C:\projects\xampp\htdocs\nc3\vendors\cakephp\cakephp\lib\Cake\Model\Model.php(3667): Model->setSource('circular_block')
#1 C:\projects\xampp\htdocs\nc3\vendors\cakephp\cakephp\lib\Cake\Model\Model.php(3038): Model->getDataSource()
#2 C:\projects\xampp\htdocs\nc3\vendors\cakephp\cakephp\lib\Cake\Model\Model.php(3010): Model->_readDataSource('all', Array)
#3 C:\projects\xampp\htdocs\nc3\app\Plugin\Nc2ToNc3\Model\Nc2ToNc3CircularNotice.php(58): Model->find('all')
#4 C:\projects\xampp\htdocs\nc3\app\Plugin\Nc2ToNc3\Model\Nc2ToNc3.php(281): Nc2ToNc3CircularNotice->migrate()
#5 C:\projects\xampp\htdocs\nc3\app\Plugin\Nc2ToNc3\Controller\Nc2ToNc3Controller.php(48): Nc2ToNc3->migration(Array)
#6 [internal function]: Nc2ToNc3Controller->migration()
#7 C:\projects\xampp\htdocs\nc3\vendors\cakephp\cakephp\lib\Cake\Controller\Controller.php(491): ReflectionMethod->invokeArgs(Object(Nc2ToNc3Controller), Array)
#8 C:\projects\xampp\htdocs\nc3\vendors\cakephp\cakephp\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 C:\projects\xampp\htdocs\nc3\vendors\cakephp\cakephp\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(Nc2ToNc3Controller), Object(CakeRequest))
#10 C:\projects\xampp\htdocs\nc3\vendors\cakephp\cakephp\lib\Cake\Core\CakeObject.php(104): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse), Array)
#11 C:\projects\xampp\htdocs\nc3\app\Plugin\Nc2ToNc3\Console\Command\Nc2ToNc3Shell.php(140): CakeObject->requestAction('nc2_to_nc3/nc2_...', Array)
#12 C:\projects\xampp\htdocs\nc3\vendors\cakephp\cakephp\lib\Cake\Console\Shell.php(462): Nc2ToNc3Shell->main()
#13 C:\projects\xampp\htdocs\nc3\vendors\cakephp\cakephp\lib\Cake\Console\ShellDispatcher.php(219): Shell->runCommand('--database', Array)
#14 C:\projects\xampp\htdocs\nc3\vendors\cakephp\cakephp\lib\Cake\Console\ShellDispatcher.php(66): ShellDispatcher->dispatch()
#15 C:\projects\xampp\htdocs\nc3\app\Console\cake.php(35): ShellDispatcher::run(Array)
#16 {main}
```

**Comment by akagane99** [comment]
https://github.com/NetCommons3/NetCommons3/issues/939
上記と同様の修正でいけそう。
