### ISSUE TITLE
新規会員登録時、アバター未指定で内部エラー発生

### ISSUE THREAD

**Issue by ponare** [NetCommons3/NetCommons3#1161]
新規会員登録でエラーとなります。

●発生状況
管理画面からの新規登録でアバターを未指定の際、
及び自動会員登録を許可して新規登録すると内部エラー。

AvatarBehavior.php で、アバターが自動生成されないようです。
非推奨とのことですがmcryptをインストールしてみましたが同じでした。

●環境
NC3.1.6
さくらVPS
CentOS 7.4.1708
PHP 7.1.13
Mariadb

●エラーログ

```
2018-01-20 06:04:03 Error: [ImagickException] non-conforming drawing primitive definition `text' @ error/draw.c/DrawImage/3282
Request URL: /nc3/users/users/download/1/avatar/thumb
Stack Trace:
#0 /var/www/html/nc3/app/Plugin/Users/Model/Behavior/AvatarBehavior.php(58): Imagick->drawimage(Object(ImagickDraw))
#1 /var/www/html/nc3/vendors/cakephp/cakephp/lib/Cake/Model/BehaviorCollection.php(238): AvatarBehavior->createAvatarAutomatically(Object(AppModel), Array)
#2 /var/www/html/nc3/vendors/cakephp/cakephp/lib/Cake/Model/Model.php(829): BehaviorCollection->dispatchMethod(Object(AppModel), Array, Array)
#3 /var/www/html/nc3/app/Plugin/Users/Model/Behavior/AvatarBehavior.php(144): Model->__call('createAvatarAut...', Array)
#4 /var/www/html/nc3/vendors/cakephp/cakephp/lib/Cake/Model/BehaviorCollection.php(238): AvatarBehavior->temporaryAvatar(Object(AppModel), Array, 'avatar', 'thumb')
#5 /var/www/html/nc3/vendors/cakephp/cakephp/lib/Cake/Model/Model.php(829): BehaviorCollection->dispatchMethod(Object(AppModel), Array, Array)
#6 /var/www/html/nc3/app/Plugin/Users/Controller/UsersAvatarController.php(125): Model->__call('temporaryAvatar', Array)
#7 /var/www/html/nc3/app/Plugin/Users/Controller/UsersAvatarController.php(71): UsersAvatarController->_downloadNoImage(Object(AppModel), Array)
#8 [internal function]: UsersAvatarController->download()
#9 /var/www/html/nc3/vendors/cakephp/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(UsersAvatarController), Array)
#10 /var/www/html/nc3/vendors/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#11 /var/www/html/nc3/vendors/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersAvatarController), Object(CakeRequest))
#12 /var/www/html/nc3/app/webroot/index.php(106): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
```

**Comment by akagane99** [comment]
ImagickExceptionエラーがでてるので、ImageMagick 関係のエラーだと思いますよ。
下記ImageMagick 関係のインストール方法です。参考まで。
https://github.com/NetCommons3/NetCommons3/wiki/ImageMagick

**Comment by ponare** [comment]
akagane99さん

ありがとうございます！
Imagemagick&Imagickをインストールしたつもりでいましたが、入ってませんでしたm(_ _)m

お陰様で解決しました。
