### ISSUE TITLE
アンケート、セッティングモード=ONで歯車マーク押すとDatabeseエラー

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#1300]
アンケートのバグではなく、コアバグかなぁ。
→(追記)アンケートバグッポイ。モデルでbeginとかしてるタイミング間違いの疑いあり。
判断つかなかったので、プラグインのラベルつけませんでした。
とりあえず報告まで。

(追記)小テストのプラグイン配置でも同様のエラーになります。

### 暫定対応
database.phpの $slave1 をまるっとコメントアウトする
/srv/nc3/public_html/app/Config/database.php
```php
/*
	public $slave1 = array(
		'datasource' => 'Database/Mysql',
		'persistent' => false,
		'host' => 'localhost',
		'port' => '3306',
(省略)
	);
*/
```

### log
```
#0    /srv/nc3/public_html/app/webroot/index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1    {main}
2018-07-25 13:53:15 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'FramesLanguage.language_id' in 'field list'
Request URL: /questionnaires/questionnaire_blocks/index?frame_id=393&page_id=251
Stack Trace:
#0    /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/Model/Datasource/DboSource.php(472): PDOStatement->execute(Array)
NetCommons3/NetCommons3#1 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/Model/Datasource/DboSource.php(438): DboSource->_execute('SELECT `Frame`....', Array)
NetCommons3/NetCommons3#2 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/Model/Datasource/DboSource.php(675): DboSource->execute('SELECT `Frame`....', Array, Array)
NetCommons3/NetCommons3#3 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/Model/Datasource/DboSource.php(1186): DboSource->fetchAll('SELECT `Frame`....', false)
NetCommons3/NetCommons3#4 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/Model/Model.php(3040): DboSource->read(Object(Frame), Array)
NetCommons3/NetCommons3#5 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/Model/Model.php(3012): Model->_readDataSource('first', Array)
NetCommons3/NetCommons3#6 /srv/nc3/public_html/app/Plugin/NetCommons/Utility/CurrentFrame.php(177): Model->find('first', Array)
NetCommons3/NetCommons3#7 /srv/nc3/public_html/app/Plugin/NetCommons/Utility/CurrentFrame.php(63): CurrentFrame->setFrame()
NetCommons3/NetCommons3#8 /srv/nc3/public_html/app/Plugin/NetCommons/Utility/Current.php(384): CurrentFrame->initialize()
NetCommons3/NetCommons3#9 /srv/nc3/public_html/app/Plugin/NetCommons/Controller/NetCommonsAppController.php(183): Current::initialize(Object(MenusController))
NetCommons3/NetCommons3#10 /srv/nc3/public_html/app/Plugin/Menus/Controller/MenusAppController.php(49): NetCommonsAppController->beforeFilter()
NetCommons3/NetCommons3#11 [internal function]: MenusAppController->beforeFilter(Object(CakeEvent))
NetCommons3/NetCommons3#12 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
NetCommons3/NetCommons3#13 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
NetCommons3/NetCommons3#14 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
NetCommons3/NetCommons3#15 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(MenusController), Object(CakeRequest))
NetCommons3/NetCommons3#16 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/Core/CakeObject.php(104): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse), Array)
NetCommons3/NetCommons3#17 /srv/nc3/public_html/app/Plugin/Frames/View/Elements/render_frames.ctp(18): CakeObject->requestAction('menus/menus/ind...', Array)
NetCommons3/NetCommons3#18 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/View/View.php(971): include('/srv/nc3/...')
NetCommons3/NetCommons3#19 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/View/View.php(933): View->_evaluate('/srv/nc3/...', Array)
NetCommons3/NetCommons3#20 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/View/View.php(1224): View->_render('/srv/nc3/...', Array)
NetCommons3/NetCommons3#21 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/View/View.php(418): View->_renderElement('/srv/nc3/...', Array, Array)
NetCommons3/NetCommons3#22 /srv/nc3/public_html/app/Plugin/Boxes/View/Helper/BoxesHelper.php(143): View->element('Frames.render_f...', Array)
NetCommons3/NetCommons3#23 [internal function]: BoxesHelper->renderFrames(Array)
NetCommons3/NetCommons3#24 /srv/nc3/public_html/app/Plugin/Pages/View/Helper/PageLayoutHelper.php(140): call_user_func_array(Array, Array)
NetCommons3/NetCommons3#25 /srv/nc3/public_html/app/Plugin/Boxes/View/Elements/render_boxes_header_footer.ctp(41): PageLayoutHelper->__call('renderFrames', Array)
NetCommons3/NetCommons3#26 /srv/nc3/public_html/app/Plugin/Boxes/View/Elements/render_boxes_header_footer.ctp(41): PageLayoutHelper->renderFrames(Array)
NetCommons3/NetCommons3#27 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/View/View.php(971): include('/srv/nc3/...')
NetCommons3/NetCommons3#28 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/View/View.php(933): View->_evaluate('/srv/nc3/...', Array)
NetCommons3/NetCommons3#29 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/View/View.php(1224): View->_render('/srv/nc3/...', Array)
NetCommons3/NetCommons3#30 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/View/View.php(418): View->_renderElement('/srv/nc3/...', Array, Array)
NetCommons3/NetCommons3#31 /srv/nc3/public_html/app/Plugin/Boxes/View/Helper/BoxesHelper.php(113): View->element('Boxes.render_bo...', Array)
NetCommons3/NetCommons3#32 [internal function]: BoxesHelper->renderBoxes('1', Array)
NetCommons3/NetCommons3#33 /srv/nc3/public_html/app/Plugin/Pages/View/Helper/PageLayoutHelper.php(140): call_user_func_array(Array, Array)
NetCommons3/NetCommons3#34 /srv/nc3/public_html/app/Plugin/Boxes/View/Elements/render_boxes.ctp(16): PageLayoutHelper->__call('renderBoxes', Array)
NetCommons3/NetCommons3#35 /srv/nc3/public_html/app/Plugin/Boxes/View/Elements/render_boxes.ctp(16): PageLayoutHelper->renderBoxes('1', Array)
NetCommons3/NetCommons3#36 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/View/View.php(971): include('/srv/nc3/...')
NetCommons3/NetCommons3#37 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/View/View.php(933): View->_evaluate('/srv/nc3/...', Array)
NetCommons3/NetCommons3#38 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/View/View.php(1224): View->_render('/srv/nc3/...', Array)
NetCommons3/NetCommons3#39 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/View/View.php(418): View->_renderElement('/srv/nc3/...', Array, Array)
NetCommons3/NetCommons3#40 /srv/nc3/public_html/app/Plugin/Pages/View/Elements/page_header.ctp(18): View->element('Boxes.render_bo...', Array)
NetCommons3/NetCommons3#41 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/View/View.php(971): include('/srv/nc3/...')
NetCommons3/NetCommons3#42 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/View/View.php(933): View->_evaluate('/srv/nc3/...', Array)
NetCommons3/NetCommons3#43 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/View/View.php(1224): View->_render('/srv/nc3/...', Array)
NetCommons3/NetCommons3#44 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/View/View.php(418): View->_renderElement('/srv/nc3/...', Array, Array)
NetCommons3/NetCommons3#45 /srv/nc3/public_html/app/Plugin/Pages/View/Helper/PageLayoutHelper.php(182): View->element('Pages.page_head...')
NetCommons3/NetCommons3#46 [internal function]: PageLayoutHelper->beforeLayout('/srv/nc3/...')
NetCommons3/NetCommons3#47 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/Utility/ObjectCollection.php(128): call_user_func_array(Array, Array)
NetCommons3/NetCommons3#48 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/View/HelperCollection.php(200): ObjectCollection->trigger(Object(CakeEvent), Array, Array)
NetCommons3/NetCommons3#49 [internal function]: HelperCollection->trigger(Object(CakeEvent))
NetCommons3/NetCommons3#50 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
NetCommons3/NetCommons3#51 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/View/View.php(524): CakeEventManager->dispatch(Object(CakeEvent))
NetCommons3/NetCommons3#52 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/View/View.php(481): View->renderLayout('', 'Pages.default')
NetCommons3/NetCommons3#53 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/Controller/Controller.php(963): View->render(NULL, NULL)
NetCommons3/NetCommons3#54 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(200): Controller->render()
NetCommons3/NetCommons3#55 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(QuestionnaireBlocksController), Object(CakeRequest))
NetCommons3/NetCommons3#56 /srv/nc3/public_html/app/webroot/index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
NetCommons3/NetCommons3#57 {main}
```

**Comment by akagane99** [comment]
@s-nakajima 対応感謝`<(_!_)>`

**Comment by akagane99** [comment]
https://github.com/NetCommons3/NetCommons/pull/489/files
修正したソースを反映して、試したみた。
残念ながらエラーになりました。

### 確認した条件

上下左右ありのレイアウト。
上、中央、右にお知らせ、左にメニューを配置

### error.log

```
2018-07-26 01:24:17 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Space.id' in 'field list'
Request URL: /setting/
Stack Trace:
#0 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/Model/Datasource/DboSource.php(472): PDOStatement->execute(Array)
#1 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/Model/Datasource/DboSource.php(438): DboSource->_execute('SELECT `Box`.`i...', Array)
#2 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/Model/Datasource/DboSource.php(675): DboSource->execute('SELECT `Box`.`i...', Array, Array)
#3 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/Model/Datasource/DboSource.php(1186): DboSource->fetchAll('SELECT `Box`.`i...', false)
#4 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/Model/Model.php(3040): DboSource->read(Object(Box), Array)
#5 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/Model/Model.php(3012): Model->_readDataSource('first', Array)
#6 /srv/nc3/public_html/app/Plugin/NetCommons/Utility/CurrentFrame.php(259): Model->find('first', Array)
#7 /srv/nc3/public_html/app/Plugin/NetCommons/Utility/CurrentFrame.php(190): CurrentFrame->setBox()
#8 /srv/nc3/public_html/app/Plugin/NetCommons/Utility/CurrentFrame.php(63): CurrentFrame->setFrame()
#9 /srv/nc3/public_html/app/Plugin/NetCommons/Utility/Current.php(388): CurrentFrame->initialize()
#10 /srv/nc3/public_html/app/Plugin/NetCommons/Controller/NetCommonsAppController.php(183): Current::initialize(Object(AnnouncementsController))
#11 [internal function]: NetCommonsAppController->beforeFilter(Object(CakeEvent))
#12 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#13 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#14 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#15 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AnnouncementsController), Object(CakeRequest))
#16 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/Core/CakeObject.php(104): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse), Array)
#17 /srv/nc3/public_html/app/Plugin/Frames/View/Elements/render_frames.ctp(18): CakeObject->requestAction('announcements/a...', Array)
#18 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/View/View.php(971): include('/srv/nc3...')
#19 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/View/View.php(933): View->_evaluate('/srv/nc3...', Array)
#20 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/View/View.php(1224): View->_render('/srv/nc3...', Array)
#21 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/View/View.php(418): View->_renderElement('/srv/nc3...', Array, Array)
#22 /srv/nc3/public_html/app/Plugin/Boxes/View/Helper/BoxesHelper.php(143): View->element('Frames.render_f...', Array)
#23 [internal function]: BoxesHelper->renderFrames(Array)
#24 /srv/nc3/public_html/app/Plugin/Pages/View/Helper/PageLayoutHelper.php(140): call_user_func_array(Array, Array)
#25 /srv/nc3/public_html/app/Plugin/Boxes/View/Elements/render_boxes_major_minor.ctp(23): PageLayoutHelper->__call('renderFrames', Array)
#26 /srv/nc3/public_html/app/Plugin/Boxes/View/Elements/render_boxes_major_minor.ctp(23): PageLayoutHelper->renderFrames(Array)
#27 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/View/View.php(971): include('/srv/nc3...')
#28 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/View/View.php(933): View->_evaluate('/srv/nc3...', Array)
#29 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/View/View.php(1224): View->_render('/srv/nc3...', Array)
#30 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/View/View.php(418): View->_renderElement('/srv/nc3...', Array, Array)
#31 /srv/nc3/public_html/app/Plugin/Boxes/View/Helper/BoxesHelper.php(123): View->element('Boxes.render_bo...', Array)
#32 [internal function]: BoxesHelper->renderBoxes('4', Array)
#33 /srv/nc3/public_html/app/Plugin/Pages/View/Helper/PageLayoutHelper.php(140): call_user_func_array(Array, Array)
#34 /srv/nc3/public_html/app/Plugin/Boxes/View/Elements/render_boxes.ctp(16): PageLayoutHelper->__call('renderBoxes', Array)
#35 /srv/nc3/public_html/app/Plugin/Boxes/View/Elements/render_boxes.ctp(16): PageLayoutHelper->renderBoxes('4', Array)
#36 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/View/View.php(971): include('/srv/nc3...')
#37 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/View/View.php(933): View->_evaluate('/srv/nc3...', Array)
#38 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/View/View.php(1224): View->_render('/srv/nc3...', Array)
#39 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/View/View.php(418): View->_renderElement('/srv/nc3...', Array, Array)
#40 /srv/nc3/public_html/app/Plugin/Pages/View/Elements/page_minor.ctp(18): View->element('Boxes.render_bo...', Array)
#41 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/View/View.php(971): include('/srv/nc3...')
#42 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/View/View.php(933): View->_evaluate('/srv/nc3...', Array)
#43 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/View/View.php(1224): View->_render('/srv/nc3...', Array)
#44 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/View/View.php(418): View->_renderElement('/srv/nc3...', Array, Array)
#45 /srv/nc3/public_html/app/Plugin/Pages/View/Helper/PageLayoutHelper.php(192): View->element('Pages.page_mino...')
#46 [internal function]: PageLayoutHelper->beforeLayout('/srv/nc3...')
#47 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/Utility/ObjectCollection.php(128): call_user_func_array(Array, Array)
#48 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/View/HelperCollection.php(200): ObjectCollection->trigger(Object(CakeEvent), Array, Array)
#49 [internal function]: HelperCollection->trigger(Object(CakeEvent))
#50 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#51 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/View/View.php(524): CakeEventManager->dispatch(Object(CakeEvent))
#52 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/View/View.php(481): View->renderLayout('', 'Pages.default')
#53 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/Controller/Controller.php(963): View->render(NULL, NULL)
#54 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(200): Controller->render()
#55 /srv/nc3/public_html/vendors/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(PagesController), Object(CakeRequest))
#56 /srv/nc3/public_html/app/webroot/index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#57 {main}
```

**Comment by s-nakajima** [comment]
Master<->SlaveのdbConfigがうまく変わらないことがあり、当現象が発生しています。
おそらく、運用としてもMaster<->Slaveで使われていないため、当機能は、一度OFFにして、Masterのみとします。
そもそも、Master<->Slaveの切り替えは、NC3で行うことでもない気がします。

**Comment by akagane99** [comment]
https://github.com/NetCommons3/NetCommons/pull/490
修正感謝！暫定対応なしで動きました。

> そもそも、Master<->Slaveの切り替えは、NC3で行うことでもない気がします。

・そうですねDB製品やロードバランサーで負荷分散できそうな気もします。
・また、現在のdatabase.phpに $master, $slave と同じDBで2つの設定があることから、コネクションって2倍になるんじゃ？と社内で意見ありました。

参考まで。

**Comment by s-nakajima** [comment]
確認はしてないので、確証はないですが、おそらく、database.phpの$slaveが書かれていても、実際にDBから取得する直前で、$useDbConfigを見て、コネクションが張られてなかったら、張ると思うんですよね。なので、大丈夫だと思っていますが・・・
