### ISSUE TITLE
速度改善 第三弾

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#1337]

**Comment by s-nakajima** [comment]
プラグインのアップデートで各プラグインのjs,css,imgをwebrootにコピーし、index.phpを通さず、直接参照するようにし、速度改善を行う。また、アップデートしてなくても、各プラグイン配下のwebrootのjs,css,imgのタイムスタンプが新しければ、そちらを参照するようにする。

**Comment by akagane99** [comment]
Revert "fix: キャッシュのパフォーマンス改善" debug=2に戻す
https://github.com/NetCommons3/NetCommons3/pull/1426

debug=0だと、NC3インストール時にmodelキャッシュ取られて内部エラーでとまった。
とりあえずdebug=2に戻す。
今後どうするかは、要検討。

### 内部エラー

* 実際のDBテーブルはある。
* 該当のmodelキャッシュのありなしは未確認でした。

```
2019-01-16 03:53:59 Error: [MissingTableException] Table users for model User was not found in datasource master.
Exception Attributes: array (
  'table' => 'users',
  'class' => 'User',
  'ds' => 'master',
)
Request URL: /install/install/init_admin_user?language=ja
Stack Trace:
#0 C:\projects\nc3-xampp\htdocs\vendors\cakephp\cakephp\lib\Cake\Model\Model.php(3673): Model->setSource('users')
#1 C:\projects\nc3-xampp\htdocs\app\Plugin\NetCommons\Model\NetCommonsAppModel.php(196): Model->getDataSource()
#2 C:\projects\nc3-xampp\htdocs\vendors\cakephp\cakephp\lib\Cake\Model\Model.php(1394): NetCommonsAppModel->getDataSource()
#3 C:\projects\nc3-xampp\htdocs\vendors\cakephp\cakephp\lib\Cake\View\Helper\FormHelper.php(215): Model->schema()
#4 C:\projects\nc3-xampp\htdocs\vendors\cakephp\cakephp\lib\Cake\View\Helper\FormHelper.php(1243): FormHelper->_introspectModel('User', 'fields', 'username')
#5 C:\projects\nc3-xampp\htdocs\vendors\cakephp\cakephp\lib\Cake\View\Helper\FormHelper.php(1180): FormHelper->_magicOptions(Array)
#6 C:\projects\nc3-xampp\htdocs\vendors\cakephp\cakephp\lib\Cake\View\Helper\FormHelper.php(1055): FormHelper->_parseOptions(Array)
#7 C:\projects\nc3-xampp\htdocs\app\Plugin\Install\View\Install\init_admin_user.ctp(39): FormHelper->input('User.username', Array)
#8 C:\projects\nc3-xampp\htdocs\vendors\cakephp\cakephp\lib\Cake\View\View.php(971): include('C:\projects\nc3...')
#9 C:\projects\nc3-xampp\htdocs\vendors\cakephp\cakephp\lib\Cake\View\View.php(933): View->_evaluate('C:\projects\nc3...', Array)
#10 C:\projects\nc3-xampp\htdocs\vendors\cakephp\cakephp\lib\Cake\View\View.php(473): View->_render('C:\projects\nc3...')
#11 C:\projects\nc3-xampp\htdocs\vendors\cakephp\cakephp\lib\Cake\Controller\Controller.php(968): View->render(NULL, NULL)
#12 C:\projects\nc3-xampp\htdocs\vendors\cakephp\cakephp\lib\Cake\Routing\Dispatcher.php(200): Controller->render()
#13 C:\projects\nc3-xampp\htdocs\vendors\cakephp\cakephp\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(InstallController), Object(CakeRequest))
#14 C:\projects\nc3-xampp\htdocs\app\webroot\index.php(121): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#15 {main}
```

### 参考：debug=2, インストール後のmodelキャッシュ（正常終了）

```
app\tmp\cache\models\myapp_cake_model_master_nc3_announcements
app\tmp\cache\models\myapp_cake_model_master_nc3_authorization_keys
app\tmp\cache\models\myapp_cake_model_master_nc3_block_role_permissions
app\tmp\cache\models\myapp_cake_model_master_nc3_block_settings
app\tmp\cache\models\myapp_cake_model_master_nc3_blocks
app\tmp\cache\models\myapp_cake_model_master_nc3_blocks_languages
app\tmp\cache\models\myapp_cake_model_master_nc3_boxes
app\tmp\cache\models\myapp_cake_model_master_nc3_boxes_page_containers
app\tmp\cache\models\myapp_cake_model_master_nc3_boxes_pages
app\tmp\cache\models\myapp_cake_model_master_nc3_categories
app\tmp\cache\models\myapp_cake_model_master_nc3_categories_languages
app\tmp\cache\models\myapp_cake_model_master_nc3_category_orders
app\tmp\cache\models\myapp_cake_model_master_nc3_containers
app\tmp\cache\models\myapp_cake_model_master_nc3_containers_pages
app\tmp\cache\models\myapp_cake_model_master_nc3_content_comments
app\tmp\cache\models\myapp_cake_model_master_nc3_data_type_choices
app\tmp\cache\models\myapp_cake_model_master_nc3_data_types
app\tmp\cache\models\myapp_cake_model_master_nc3_default_role_permissions
app\tmp\cache\models\myapp_cake_model_master_nc3_external_idp_users
app\tmp\cache\models\myapp_cake_model_master_nc3_frame_public_languages
app\tmp\cache\models\myapp_cake_model_master_nc3_frames
app\tmp\cache\models\myapp_cake_model_master_nc3_frames_languages
app\tmp\cache\models\myapp_cake_model_master_nc3_groups
app\tmp\cache\models\myapp_cake_model_master_nc3_groups_users
app\tmp\cache\models\myapp_cake_model_master_nc3_languages
app\tmp\cache\models\myapp_cake_model_master_nc3_likes
app\tmp\cache\models\myapp_cake_model_master_nc3_likes_users
app\tmp\cache\models\myapp_cake_model_master_nc3_list
app\tmp\cache\models\myapp_cake_model_master_nc3_mail_queue_users
app\tmp\cache\models\myapp_cake_model_master_nc3_mail_queues
app\tmp\cache\models\myapp_cake_model_master_nc3_mail_setting_fixed_phrases
app\tmp\cache\models\myapp_cake_model_master_nc3_mail_settings
app\tmp\cache\models\myapp_cake_model_master_nc3_menu_frame_settings
app\tmp\cache\models\myapp_cake_model_master_nc3_menu_frames_pages
app\tmp\cache\models\myapp_cake_model_master_nc3_menu_frames_rooms
app\tmp\cache\models\myapp_cake_model_master_nc3_notifications
app\tmp\cache\models\myapp_cake_model_master_nc3_page_containers
app\tmp\cache\models\myapp_cake_model_master_nc3_pages
app\tmp\cache\models\myapp_cake_model_master_nc3_pages_languages
app\tmp\cache\models\myapp_cake_model_master_nc3_plugins
app\tmp\cache\models\myapp_cake_model_master_nc3_plugins_roles
app\tmp\cache\models\myapp_cake_model_master_nc3_plugins_rooms
app\tmp\cache\models\myapp_cake_model_master_nc3_roles
app\tmp\cache\models\myapp_cake_model_master_nc3_roles_rooms
app\tmp\cache\models\myapp_cake_model_master_nc3_roles_rooms_users
app\tmp\cache\models\myapp_cake_model_master_nc3_room_role_permissions
app\tmp\cache\models\myapp_cake_model_master_nc3_room_roles
app\tmp\cache\models\myapp_cake_model_master_nc3_rooms
app\tmp\cache\models\myapp_cake_model_master_nc3_rooms_languages
app\tmp\cache\models\myapp_cake_model_master_nc3_schema_migrations
app\tmp\cache\models\myapp_cake_model_master_nc3_site_settings
app\tmp\cache\models\myapp_cake_model_master_nc3_spaces
app\tmp\cache\models\myapp_cake_model_master_nc3_tags
app\tmp\cache\models\myapp_cake_model_master_nc3_tags_contents
app\tmp\cache\models\myapp_cake_model_master_nc3_topic_frame_settings
app\tmp\cache\models\myapp_cake_model_master_nc3_topic_frames_blocks
app\tmp\cache\models\myapp_cake_model_master_nc3_topic_frames_plugins
app\tmp\cache\models\myapp_cake_model_master_nc3_topic_frames_rooms
app\tmp\cache\models\myapp_cake_model_master_nc3_topic_readables
app\tmp\cache\models\myapp_cake_model_master_nc3_topic_user_statuses
app\tmp\cache\models\myapp_cake_model_master_nc3_topics
app\tmp\cache\models\myapp_cake_model_master_nc3_upload_files
app\tmp\cache\models\myapp_cake_model_master_nc3_upload_files_contents
app\tmp\cache\models\myapp_cake_model_master_nc3_user_attribute_choices
app\tmp\cache\models\myapp_cake_model_master_nc3_user_attributes
app\tmp\cache\models\myapp_cake_model_master_nc3_user_role_settings
app\tmp\cache\models\myapp_cake_model_master_nc3_user_select_counts
app\tmp\cache\models\myapp_cake_model_master_nc3_users
app\tmp\cache\models\myapp_cake_model_master_nc3_users_languages
app\tmp\cache\models\myapp_cake_model_master_nc3_workflow_comments
app\tmp\cache\models\myapp_netcommons_model_master_data_type_choices_3_2_1
app\tmp\cache\models\myapp_netcommons_model_master_data_types_3_2_1
app\tmp\cache\models\myapp_netcommons_model_master_languages_3_2_1
app\tmp\cache\models\myapp_netcommons_model_master_languages_3_2_2
app\tmp\cache\models\myapp_netcommons_model_master_plugins_3_2_1
app\tmp\cache\models\myapp_netcommons_model_master_site_settings_3_2_2
app\tmp\cache\models\myapp_netcommons_model_master_spaces_3_2_1
app\tmp\cache\models\myapp_netcommons_model_master_spaces_3_2_2
```

**Comment by s-nakajima** [comment]
一度クローズする。
https://github.com/NetCommons3/NetCommons3/issues/1468
