### ISSUE TITLE
施設予約、予約できない

### ISSUE THREAD

**Issue by ghost** [NetCommons3/NetCommons3#1387]
- NC 3.2.1
- macOS High Sierra
- Google Chrome
- パブリックスペースに施設予約プラグインを配置。
- 施設を１個登録。
- ユーザは、サイト管理者権限を有し、パブリックスペースではルーム管理者となっている。

#### 操作手順とNCの反応
下図で、12月6日の「+」アイコンをクリックした。
![2018-12-05 14 36 47](https://user-images.githubusercontent.com/7931689/49492603-4e79ec80-f89c-11e8-8598-4266de0a5bf9.png)

すると次のように「このアカウントでは、指定したURLにアクセスができません。」と怒られます。
![2018-12-05 14 35 15](https://user-images.githubusercontent.com/7931689/49492623-681b3400-f89c-11e8-8de6-d699887c149c.png)

error.logの中身は次のとおりです。
`````
2018-12-05 05:36:49 Error: [ForbiddenException] アクセスができません。
Request URL: /reservations/reservation_plans/add?frame_id=25&year=2018&month=12&day=6&location_key=9068842ed9c55508a05d9089ee7efa2e
Stack Trace:
#0 /virtual/htdocs/www3/vendors/cakephp/cakephp/lib/Cake/Utility/ObjectCollection.php(129): ReservationPermissionComponent->startup(Object(ReservationPlansController))
#1 /virtual/htdocs/www3/vendors/cakephp/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#2 /virtual/htdocs/www3/vendors/cakephp/cakephp/lib/Cake/Controller/Controller.php(678): CakeEventManager->dispatch(Object(CakeEvent))
#3 /virtual/htdocs/www3/vendors/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#4 /virtual/htdocs/www3/vendors/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ReservationPlansController), Object(CakeRequest))
#5 /virtual/htdocs/www3/app/webroot/index.php(120): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
`````

**Comment by ghost** [comment]
施設（上の例では「TEM電顕」）の設定には問題がないです。「予約できる権限」は「一般」以上ですし、「予約を受け付けるルーム」も「パブリック」を選択してあります。
「個人的な予約を受け付ける」という奇異なチェックボックスがありますが、これはどういう意味だろう???
![2018-12-05 14 53 44](https://user-images.githubusercontent.com/7931689/49493032-e0cec000-f89d-11e8-8e7a-3238c292f486.png)

**Comment by akagane99** [comment]
* NC3.2.1.1
* VPS
* Google Chrome（windows10）
* パブリックスペースに施設予約プラグインを配置。
* 施設を１個登録。
* ユーザは、サイト管理者権限を有し、パブリックスペースではルーム管理者となっている。

上記で予約できました。
環境の調子わるのかなぁ。

![image](https://user-images.githubusercontent.com/2756509/49494931-b5030880-f8a4-11e8-96ac-92a8ddcedd96.png)

**Comment by ghost** [comment]
試していただきありがとうございます。うーん、どういうことだろう💦
NC 3.2.1.1にアップデートしてみましたが、やはり「このアカウントでは、指定したURLにアクセスができません」と怒られました(>_<)
当方のより詳しい環境は次のとおりです。

- PHP 7.1.23
- MySQL 5.6.36
- Apache バージョン不明
- WAF は OFF
- サーバはZenlogic (VPSタイプだがshellは使えない)

テーマをMichael the 5thにするとOKとかw

**Comment by ghost** [comment]
Windows 10上のGoogle Chromeからアクセスしてみましたが、やはり「このアカウントでは、指定したURLにアクセスができません」と怒られました(>_<)
サーバ側が何か違うのかな・・・

実は、NC3の施設予約プラグインを使うのは初めてなんです。これまでどうだったかはわからないです。。。

**Comment by ghost** [comment]
わかりました！
セッティングモードON →　施設予約プラグインの歯車アイコン　→　「施設設定」タブ　→　（1個だけしか施設が登録されていない場合の、その施設の）「編集」ボタン　→　「予約を受け付けるルーム」項。

この項目で、「全てのルームから予約を受け付ける」のチェックが外れており、「パブリック」にのみチェックが入っている場合に、（例えパブリックスペースからであっても）予約しようとすると「このアカウントでは、指定したURLにアクセスができません」と怒られます。結構、条件が重ならないと発症しませんが、一発で地雷を踏んでしまいました。

#1386 も同じ条件で発症します。

**Comment by akagane99** [comment]
* NC3.2.1.1
* VPS
  * php5.4
* Google Chrome（windows10）
* パブリックスペースに施設予約プラグインを配置。
* 施設管理
  * 施設を１個登録。
  * セッティングモードON →　施設予約プラグインの歯車アイコン　→　「施設設定」タブ　→　（1個だけしか施設が登録されていない場合の、その施設の）「編集」ボタン　→　「予約を受け付けるルーム」項。
    * この項目で、「全てのルームから予約を受け付ける」のチェックが外れており、「パブリック」にのみチェックが入っている
* ユーザは、サイト管理者権限を有し、パブリックスペースではルーム管理者となっている。

上記で予約できました。
ログイン中、「パブリック」からは予約登録でき、
パブリックの「サブルーム」では予約登録できない状態になりました。

なんだろう？
今のところは、phpのバージョンが違いますね。
本格的にデバックしてみないと、問題特定できなそうな気がしました。

**Comment by akagane99** [comment]
### エラーログ
https://github.com/NetCommons3/NetCommons3/issues/1387#issue-387602733
> Request URL: /reservations/reservation_plans/add?frame_id=25&year=2018&month=12&day=6&location_key=9068842ed9c55508a05d9089ee7efa2e

### デバック箇所案

ここらへんかなぁ。

* 上記エラーから、ReservationPlansController.php呼び出されたとこでエラー。
  * https://github.com/NetCommons3/Reservations/blob/master/Controller/ReservationPlansController.php#L94
  * このコントローラのコンポーネントで'Reservations.ReservationPermission',を呼び出し。
    * https://github.com/NetCommons3/Reservations/blob/master/Controller/Component/ReservationPermissionComponent.php#L54
    * ReservationPermissionComponent.phpのstartup()は、ReservationPlansControllerの実行時全てで呼び出される。startup()でaddアクション時に$this->_canCreate()でチェックしてる
      * https://github.com/NetCommons3/Reservations/blob/master/Controller/Component/ReservationPermissionComponent.php#L82
      * $this->_canCreate()、見た感じ、大した処理をしてるわけではなさそう。うーん。

パッと見調査はこんな感じでした。
参考まで。
