### ISSUE TITLE
キャビネット、アップロードファイル格納位置変更の影響で解凍できない

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#1389]
NC3.2.1.1で再現しました。

### 掲示板より
https://www.netcommons.org/bbses/bbs_articles/view/778/cbea03bd872c23a5c5d5d4590930031c?frame_id=199#!#%2Fbbs-article-161
> 多分ですが、アップロードしたファイルの格納位置を変える修正が3.2（3.1.10？）にあったと思いますが、その時の修正もれかなあと思います。

#### （参考）3.2.0でzipファイルが解凍できなかったときのエラーログ

cat nc320/app/tmp/logs/error.log
```
2018-10-02 08:06:48 Error: [InternalErrorException] UnZip Failed.
Request URL: /nc320/cabinets/cabinet_files_edit/unzip/5/17af74ac63045ab1be1c1fcbe933d76f?frame_id=6
Stack Trace:
#0 [internal function]: CabinetUnzipBehavior->unzip(Object(CabinetFile), Array)
#1 /var/www/html/nc320/vendors/cakephp/cakephp/lib/Cake/Model/BehaviorCollection.php(239): call_user_func_array(Array, Array)
#2 /var/www/html/nc320/vendors/cakephp/cakephp/lib/Cake/Model/Model.php(829): BehaviorCollection->dispatchMethod(Object(CabinetFile), 'unzip', Array)
#3 /var/www/html/nc320/app/Plugin/Cabinets/Controller/CabinetFilesEditController.php(646): Model->__call('unzip', Array)
#4 /var/www/html/nc320/app/Plugin/Cabinets/Controller/CabinetFilesEditController.php(646): CabinetFile->unzip(Array)
#5 [internal function]: CabinetFilesEditController->unzip()
#6 /var/www/html/nc320/vendors/cakephp/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(CabinetFilesEditController), Array)
#7 /var/www/html/nc320/vendors/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#8 /var/www/html/nc320/vendors/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(CabinetFilesEditController), Object(CakeRequest))
#9 /var/www/html/nc320/app/webroot/index.php(121): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
```

### 修正参考
https://github.com/NetCommons3/PhotoAlbums/commit/3b58e7a10660ad288b3ded5c05b9d51e951b9f76

アップロードファイル格納位置変更の影響は、他にもあるかもです。

**Comment by akagane99** [comment]
対応しました。動作確認ずみです。
https://github.com/NetCommons3/Cabinets/pull/63/files

対象
https://github.com/NetCommons3/NetCommons3/issues/1390
