### ISSUE TITLE
[github最新開発版] お知らせ、プラグイン配置後の書き込みでエラーになる

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#1438]
開発でgithubより最新取得しました。
（NC3.2.2リリース版では、このエラー発生しませんでした。）

環境PC
windows10 + chrome
windows10 + IE11
管理＞システム管理＞開発者向け（タブ）＞デバッグ出力レベル=2

* お知らせで、プラグイン配置後にお知らせの内容を書き込む
* お知らせを「編集」する。（ブロック設定入らず、表の「編集」ボタン押下）
と以下のエラーがでました。

#### デバッグ出力レベル=2
```
2019-01-23 02:29:03 Error: [AuthSecurityException] '_Token.fields' was not found in request data.
Request URL: /setting/announcements/announcements/edit?frame_id=8&page_id=5
Stack Trace:
#0 /var/www/app/vendors/cakephp/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(490): SecurityComponent->_validToken(Object(AnnouncementsController))
#1 /var/www/app/vendors/cakephp/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(247): SecurityComponent->_validatePost(Object(AnnouncementsController))
#2 [internal function]: SecurityComponent->startup(Object(AnnouncementsController))
#3 /var/www/app/vendors/cakephp/cakephp/lib/Cake/Utility/ObjectCollection.php(129): call_user_func_array(Array, Array)
#4 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#5 /var/www/app/vendors/cakephp/cakephp/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#6 /var/www/app/vendors/cakephp/cakephp/lib/Cake/Controller/Controller.php(683): CakeEventManager->dispatch(Object(CakeEvent))
#7 /var/www/app/vendors/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#8 /var/www/app/vendors/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AnnouncementsController), Object(CakeRequest))
#9 /var/www/app/app/webroot/index.php(121): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
```

#### デバッグ出力レベル=0
```
予期しないトークンにより、登録が正常にできませんでした。
```

* セッティングモード＝ONにして、歯車マーク＞「追加」及び「編集」でお知らせを書いた時は大丈夫でした。
* 参考：ウィジウィグの不具合かと思い、ブログでウィジウィグを使って記事を書きましたが、大丈夫でした。

とりあえず報告まで。

### 対応プラグイン（Form->createで検索. 目検する）
 - [x] お知らせ
 - [x] Auth
 - [x] AuthorizationKeys(修正なし)
 - [x] 掲示板
 - [x] Blocks(修正なし)
 - [x] ブログ(修正なし)
 - [x] Boxes(修正なし)
 - [x] キャビネット(修正なし)
 - [x] カレンダー
circular notice 
コンテンツコメント
Question
CircularNotices
Frame
Groups
Holiday
Install　
Multidatabases　までチェック済み
Registrations　までチェック済み3/1

**Comment by akagane99** [comment]
### お知らせ以外、プラグイン調査
* Form->createで検索. 目検する。
* BlockIndex->createで検索. 目検する。
  * BlockIndex->create内で、NetCommonsForm->createしてる。
  * BlockIndex->endとセット（実体はNetCommonsForm->endと同じ）

### ざっくり影響箇所

https://github.com/search?l=PHP&q=org%3ANetCommons3+Form-%3Ecreate&type=Code

**Comment by akagane99** [comment]
最近composerでインストールしたNC3.2.1.1でも同じ症状でました。
おおよそ、違いはJSライブラリかなと思い、大丈夫なNC3.2.1.1とダメなやつと比較しました。

bowerはcomposerと違い、lockファイルの仕組みがないため、インストール時期によってJSライブラリのバージョンがずれるようです。
参考まで。


(追記)
#### トークンエラーでる方（NC3.2.1.1   composerインストール最近）

下記JSライブラリのバージョンが上がってました。

プラグイン名 | パッケージ | バージョン
-- | -- | --
angular | angular/bower-angular | 1.7.6 (3d45fe73a8)
angular-animate | angular/bower-angular-animate | 1.7.6 (e6b6ca95ac)
angular-mocks | angular/bower-angular-mocks | 1.7.6 (8e0088c1a2)
moment | moment/moment | 2.24.0 (8a6b2e1120)

※ また、NC3.2.2公式.zipの上記JSライブラリは、バージョン上がってなかったです。


(更新)
[JSバージョン比較.xlsx](https://github.com/NetCommons3/NetCommons3/files/2802172/JS.xlsx)

**Comment by akagane99** [comment]
@s-nakajima 
全プラグインチェック終わりました。
問題ある個所は修正しました。
