### ISSUE TITLE
メニュー表示順変更できない

### ISSUE THREAD

**Issue by dreamer9999** [NetCommons3/NetCommons3#1478]
メニュー表示順変更しようとしましたが、エラーになります。
メニュー3項目「ホーム/hoge/fuga」あるとして、最下の「fuga」を一つ上に移動しようとして、メニューのページ設定で表示される移動ボタン矢印「↑」を押しますがエラーになります。
当方の環境は、さくらレンタルサーバー、Apache/2.4.38、MySQL 5.7、PHP 7.2.14　 です。
※　私の操作方法・セッティング間違え起因での障害で、他の方では障害おきていないのかもしれませんが、、、一応記載させていただきます。

エラーログは下記です。

2019-04-02 12:13:33 Error: [BadRequestException] 不正なリクエストの可能性があります。
Request URL: /pages/pages_edit/move
Stack Trace:
#0 /home/hoge/www/fuga/vendors/cakephp/cakephp/lib/Cake/Controller/Controller.php(883): NetCommonsAppController->throwBadRequest()
#1 /home/hoge/www/fuga/app/Plugin/Pages/Controller/PagesEditController.php(89): Controller->setAction('throwBadRequest')
#2 /home/hoge/www/superi/vendors/cakephp/cakephp/lib/Cake/Event/CakeEventManager.php(243): PagesEditController->beforeFilter(Object(CakeEvent))
#3 /home/hoge/www/fuga/vendors/cakephp/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch(Object(CakeEvent))
#4 /home/hoge/www/fuga/vendors/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#5 /home/hoge/www/fuga/vendors/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(PagesEditController), Object(CakeRequest))
#6 /home/hoge/www/fuga/app/webroot/index.php(120): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}

**Comment by dreamer9999** [comment]
上記は、「セッティングモードOＮ」中に、「ページ設定」を行うときの現象でした。

・「セッティングモードOFF」＋「ページ設定」
　　　　　メニューの移動矢印、編集ボタン、ページ追加ボタン、３種類全て機能する。
・「セッティングモードOＮ」＋「ページ設定」
　　　　　上記３種機能のうち　メニューの移動矢印　だけ機能しない。ので、機能するように改善していただきたいです。

![ページ設定](https://user-images.githubusercontent.com/3895089/55660922-b7ba3e00-5843-11e9-83c5-307a38a94403.jpg)

**Comment by RikaFujiwara** [comment]
バージョン3.3.2ではこの現象、発生しないようです。
