### ISSUE TITLE
汎用DBで多言語＋編集時、言語切り替えを行うとBadRequest

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#1509]
github最新版で確認しました。
とりあえず報告まで。

他のプラグインの動作例として、お知らせでは編集時、言語切り替えを行っても、エラーにならず切替られました。

## エラーログ

```
2019-06-06 05:09:48 Error: [BadRequestException] Bad Request
Request URL: /multidatabases/multidatabase_contents/edit/5/0509b7d1cdf4e0cac96ac8a2179d849a?frame_id=7
Stack Trace:
#0 /var/www/app/app/Plugin/Multidatabases/Controller/MultidatabaseContentsController.php(255): NetCommonsAppController->throwBadRequest()
#1 [internal function]: MultidatabaseContentsController->edit()
#2 /var/www/app/vendors/cakephp/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(MultidatabaseContentsController), Array)
#3 /var/www/app/vendors/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#4 /var/www/app/vendors/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(MultidatabaseContentsController), Object(CakeRequest))
#5 /var/www/app/app/webroot/index.php(121): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
```

**Comment by RikaFujiwara** [comment]
3.3.2で確認しました。どうも編集時に限らず、詳細表示しているときにも発生します。
一覧表示での切り替えではOKでした。
