### ISSUE TITLE
新規登録の受付を行うとトークンエラー #457　は解決していない？

### ISSUE THREAD

**Issue by T-Yoshinori** [NetCommons3/NetCommons3#1640]
3.3.3でも新規登録受付で、「次へ」を押すと、トークンエラーが発生します。

**Comment by T-Yoshinori** [comment]
2021-05-06 10:58:49 Error: [AuthSecurityException] The request has been black-holed
Request URL: /auth/auto_user_regist/request
Stack Trace:
#0 /var/www/html/vendors/cakephp/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(247): SecurityComponent->_validatePost()
#1 /var/www/html/vendors/cakephp/cakephp/lib/Cake/Utility/ObjectCollection.php(129): SecurityComponent->startup()
#2 /var/www/html/vendors/cakephp/cakephp/lib/Cake/Event/CakeEventManager.php(244): ObjectCollection->trigger()
#3 /var/www/html/vendors/cakephp/cakephp/lib/Cake/Controller/Controller.php(683): CakeEventManager->dispatch()
#4 /var/www/html/vendors/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#5 /var/www/html/vendors/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#6 /var/www/html/app/webroot/index.php(131): Dispatcher->dispatch()
