### ISSUE TITLE
bake modelでError: Table top_pages for model TopPage was not found in datasource slave1.

### ISSUE THREAD

**Issue by RyujiAMANO** [NetCommons3/NetCommons3#41]
https://github.com/NetCommons3/NetCommons3/blob/master/app/Model/Room.php
でTopPageモデルとアソシエーションしてるのが原因っぽい

Trackableから順次リレーションたどってRoomにいきつくっぽい

以下エラーメッセージ
Error: Table top_pages for model TopPage was not found in datasource slave1.
#0 /var/www/app/lib/Cake/Model/Model.php(3498): Model->setSource('top_pages')
#1 /var/www/app/lib/Cake/Model/Model.php(1355): Model->getDataSource()
#2 /var/www/app/lib/Cake/Model/Model.php(1447): Model->schema()
#3 /var/www/app/app/Plugin/NetCommons/Model/Behavior/TrackableBehavior.php(67): Model->hasField('created_user')
#4 /var/www/app/app/Plugin/NetCommons/Model/Behavior/TrackableBehavior.php(53): TrackableBehavior->_hasTrackableFields(Object(AppModel))
#5 /var/www/app/lib/Cake/Model/BehaviorCollection.php(145): TrackableBehavior->setup(Object(AppModel), Array)
#6 /var/www/app/lib/Cake/Model/BehaviorCollection.php(66): BehaviorCollection->load('NetCommons.Trac...', Array)
#7 /var/www/app/lib/Cake/Model/Model.php(747): BehaviorCollection->init('TopPage', Array)
#8 /var/www/app/app/Plugin/NetCommons/Model/NetCommonsAppModel.php(79): Model->__construct(Array, NULL, NULL)
#9 /var/www/app/lib/Cake/Utility/ClassRegistry.php(185): NetCommonsAppModel->__construct(Array)
#10 /var/www/app/lib/Cake/Model/Model.php(1048): ClassRegistry::init(Array)
#11 /var/www/app/lib/Cake/Model/Model.php(859): Model->_constructLinkedModel('TopPage', 'TopPage', NULL)
#12 /var/www/app/lib/Cake/Model/Model.php(892): Model->__isset('TopPage')
#13 /var/www/app/lib/Cake/Console/Command/Task/TestTask.php(394): Model->__get('TopPage')
#14 /var/www/app/lib/Cake/Console/Command/Task/TestTask.php(396): TestTask->_processModel(Object(Room))
#15 /var/www/app/lib/Cake/Console/Command/Task/TestTask.php(396): TestTask->_processModel(Object(Group))
#16 /var/www/app/lib/Cake/Console/Command/Task/TestTask.php(396): TestTask->_processModel(Object(User))
#17 /var/www/app/lib/Cake/Console/Command/Task/TestTask.php(396): TestTask->_processModel(Object(AppModel))
#18 /var/www/app/lib/Cake/Console/Command/Task/TestTask.php(376): TestTask->_processModel(Object(Tag))
#19 /var/www/app/lib/Cake/Console/Command/Task/TestTask.php(146): TestTask->generateFixtureList(Object(Tag))
#20 /var/www/app/lib/Cake/Console/Command/Task/ModelTask.php(854): TestTask->bake('Model', 'Tag')
#21 /var/www/app/lib/Cake/Console/Command/Task/ModelTask.php(109): ModelTask->bakeTest('Tag')
#22 /var/www/app/lib/Cake/Console/Shell.php(431): ModelTask->execute()
#23 /var/www/app/lib/Cake/Console/Shell.php(428): Shell->runCommand('execute', Array)
#24 /var/www/app/lib/Cake/Console/ShellDispatcher.php(207): Shell->runCommand('model', Array)
#25 /var/www/app/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#26 /var/www/app/app/Console/cake.php(35): ShellDispatcher::run(Array)
#27 {main}

**Comment by RyujiAMANO** [comment]
bake時にAppModelが使われるが、AppModelがNetCommonsAppModelを継承しててNetCommonsAppModelでTrackableついてるからかな
